# Generated by Django 4.2.3 on 2023-07-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_nuser_status_alter_nuser_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='net_cover',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='文件网络路径'),
        ),
    ]
